### ISSUE TITLE
Keywords in portal_parser.py

### ISSUE THREAD

**Issue by WaqarSM** [sahilsk11/resume-scanner#3]
Should the `Keywords` list in `portal_parser.py` also account for capitalizations? 

eg. C++ vs c++, or python vs Python.

I reckon this should handle it:

```Python
portal_parser.py L26: 

keywordsCap = [keyword.capitalize() for keyword in keywords]
Keywords.append(keywordsCap)
```

Cheers 🚀

**Comment by Saaniya00** [comment]
Hi, thanks for bringing that up! We actually did a case insensitive search for all keywords found in portal_parser and the web portal that we were looking at, this was done locally and then added to our list.
