### ISSUE TITLE
Leaked Mongo instance in db_connection.py

### ISSUE THREAD

**Issue by BonitaTerror** [sahilsk11/resume-scanner#4]
Hello, saw this on tik tok. I noticed the password for your mongo instance is imported from some module that isn't included in the repo (which is good), but the username and uri are in the file. I feel that these should be put into an environment variable, especially if it's the same instance you use for glidecv.com. I can do so if you would accept a PR :smile:

**Comment by sahilsk11** [comment]
Just created a new DB user specifically for this instance and moved username to another file. Thanks!
